services:

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - gamelib_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - RAWG_API_KEY=${RAWG_API_KEY}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - gamelib_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:3000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gamelib_network

# Volumes
volumes:
  mongo_data:
    driver: local

# Networks
networks:
  gamelib_network:
    driver: bridge
